name: daily
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 12 * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      DATABASE: ${{ secrets.DATABASE }}
      SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Run Python script
        run: python main.py
