name: daily
on: 
  push:
    branches: 
      - 'main'
  schedule:
    - cron: '0 12 * * *'

jobs:
  run-python-script: 
    runs-on: ubuntu-latest
    env:
      CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
      SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Add credentials.json 
        run: echo "$CREDENTIALS_JSON" | base64 --decode > credentials.json 

      - name: Add service_account.json
        run: echo "$SERVICE_ACCOUNT_JSON" | base64 --decode > service_account.json
      
      - name: Run Python script 
        run: python main.py

          
      
  
