name: daily
on: 
  push:
    branches: 
      - 'main'
  schedule:
    - cron: '0 12 * * *'

jobs:
  run-python-script: 
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Add credentials.json 
        run: echo "$CREDENTIALS_JSON" > credentials.json 
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}

      - name: Debug
        run: echo "Length of CREDENTIALS_JSON is$(printf '%s' "${{ CREDENTIALS_JSON }}" | wc -c)"
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          
      
      - name: Run Python script 
        run: python main.py
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          
      
  
